"""Extractor quality measurement and its freshness gate (ingestion §7.4, §16).

Two things are tested here and they are different.

The **measurement functions** are checked against the synthetic fixture set, so
the harness itself is known to work -- a quantile that is wrong on a one-chunk
source, or a coverage ratio that divides by the wrong denominator, would make
every future measurement quietly meaningless.

The **freshness gate** is what makes §7.4 a discipline. It fails CI when the
recorded measurement was taken under a different extractor or normalizer than
the code is running, which is the mechanism that stops an extractor upgrade
landing with a stale number attached to it.

The recorded baseline lives at ``tests/ingestion/extraction_baseline.json`` and
is regenerated by ``scripts/measure_extraction.py``. It records synthetic
fixtures, not the real corpus -- §18 open question 1 is explicit that the real
numbers are unmeasured, and a baseline built from reportlab output must not be
mistaken for one.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

import pytest

from studium.ingestion.extract import get_extractor
from studium.ingestion.measure import (
    MIN_COVERAGE_RATIO,
    MIN_FIXTURE_SOURCES,
    Measurement,
    SourceMeasurement,
    build_measurement,
    check_freshness,
    load,
    measure_pages,
    render,
)
from studium.ingestion.normalize import NORMALIZER_VERSION
from tests.fixtures import pdfs

BASELINE = Path(__file__).parent / "extraction_baseline.json"


def _measure_fixture(tmp_path: Path, name: str) -> SourceMeasurement:
    path = pdfs.BUILDERS[name](tmp_path / f"{name}.pdf")
    content = asyncio.run(get_extractor().extract(path))
    return measure_pages(
        name,
        [(page.page_number, page.text) for page in content.pages],
        section_hierarchies=[page.section_hierarchy for page in content.pages],
    )


# --- the harness itself ----------------------------------------------------


@pytest.mark.parametrize("name", sorted(pdfs.BUILDERS))
def test_every_fixture_measures(tmp_path: Path, name: str) -> None:
    measurement = _measure_fixture(tmp_path, name)
    assert measurement.chunks > 0, f"{name} produced no chunks to measure"
    assert measurement.chunk_token_median > 0
    assert measurement.extracted_tokens > 0


def test_quartiles_are_ordered(tmp_path: Path) -> None:
    measurement = _measure_fixture(tmp_path, "simple")
    assert measurement.chunk_token_q1 <= measurement.chunk_token_median
    assert measurement.chunk_token_median <= measurement.chunk_token_q3


def test_a_single_chunk_source_measures_without_crashing() -> None:
    """``statistics.quantiles`` raises below two data points; this must not.

    A one-chunk source is a legitimate measurement -- a short paper, a fixture
    -- and a harness that throws on it silently drops the smallest sources out
    of every corpus-wide number.
    """
    measurement = measure_pages("one-chunk", [(1, "A short page of prose.")])
    assert measurement.chunks >= 1
    assert measurement.chunk_token_median > 0


def test_an_empty_source_measures_to_zero() -> None:
    measurement = measure_pages("empty", [(1, "")])
    assert measurement.chunks == 0
    assert measurement.chunk_token_median == 0.0
    assert measurement.coverage_ratio == 0.0


def test_coverage_is_measured_against_the_reference(tmp_path: Path) -> None:
    """§7.4: extracted tokens over an independent count.

    The failure this catches is an extractor that never saw half the document:
    its chunk-size distribution looks perfectly healthy for the text it did
    get, and only a comparison against something else reveals the gap.
    """
    pages = [(1, "word " * 200)]
    generous = measure_pages("half", pages, reference_tokens=1000)
    assert generous.coverage_ratio < MIN_COVERAGE_RATIO
    assert not generous.covers_enough

    exact = measure_pages("full", pages, reference_tokens=None)
    assert exact.covers_enough


def test_section_detection_is_reported(tmp_path: Path) -> None:
    """A heading heuristic that stops firing costs retrieval its breadcrumbs."""
    measurement = _measure_fixture(tmp_path, "simple")
    assert measurement.sectioned_chunk_ratio > 0, (
        "no chunk carried a section_path; heading detection produced nothing"
    )


def test_low_coverage_sources_are_named() -> None:
    measurement = build_measurement(
        extractor_version="x/1",
        sources=[
            measure_pages("good", [(1, "word " * 200)]),
            measure_pages("bad", [(1, "word " * 200)], reference_tokens=10_000),
        ],
    )
    assert measurement.low_coverage == ("bad",)


def test_render_is_readable() -> None:
    measurement = build_measurement(
        extractor_version="pdfplumber/0.0", sources=[measure_pages("s", [(1, "a b c")])]
    )
    output = render(measurement)
    assert "pdfplumber/0.0" in output
    assert "pooled median chunk size" in output


def test_measurement_round_trips_through_json() -> None:
    """The baseline is a file, so it has to survive serialisation exactly."""
    original = build_measurement(
        extractor_version="pdfplumber/1.2.3",
        sources=[measure_pages("s", [(1, "some prose here")])],
    )
    assert Measurement.from_json(original.to_json()) == original


# --- §7.4's freshness gate -------------------------------------------------


def test_freshness_passes_when_versions_match() -> None:
    recorded = build_measurement(extractor_version="pdfplumber/0.11.10", sources=[])
    result = check_freshness(
        recorded,
        extractor_version="pdfplumber/0.11.10",
        normalizer_version=NORMALIZER_VERSION,
    )
    assert result.fresh


def test_freshness_fails_on_an_extractor_change() -> None:
    """The check §7.4 asks for, and the reason it exists.

    An extractor swap with a stale measurement attached is exactly the
    "intuition rather than measurement" the section forbids -- and the three
    extractors that differed three-fold in median chunk size are the evidence
    that intuition is not up to the job.
    """
    recorded = build_measurement(extractor_version="pdfplumber/0.11.10", sources=[])
    result = check_freshness(
        recorded,
        extractor_version="marker/1.0",
        normalizer_version=NORMALIZER_VERSION,
    )
    assert not result.fresh
    assert "marker/1.0" in result.reason
    assert "re-measurement" in result.reason.lower() or "re-run" in result.reason.lower()


def test_freshness_fails_on_a_normalizer_change() -> None:
    """A normalisation change moves the distribution as surely as an extractor one.

    Adding a transformation changes what survives to be chunked. A measurement
    naming only the extractor would still look current, which is why both
    versions are recorded and both are checked.
    """
    recorded = build_measurement(extractor_version="pdfplumber/0.11.10", sources=[])
    result = check_freshness(
        recorded,
        extractor_version="pdfplumber/0.11.10",
        normalizer_version="studium.normalize/9.9",
    )
    assert not result.fresh
    assert "studium.normalize/9.9" in result.reason


# --- the recorded baseline -------------------------------------------------


def test_the_baseline_exists() -> None:
    assert BASELINE.exists(), (
        f"{BASELINE.name} is missing. Generate it with "
        f"`python scripts/measure_extraction.py --write`."
    )


def test_the_baseline_is_fresh() -> None:
    """§7.4's CI check, run against the committed baseline.

    This is the test that fails when someone upgrades pdfplumber without
    re-measuring. The fix is to run the script, look at whether the numbers
    moved, and commit the new file -- looking at them is the point, so the
    script prints a table rather than only writing JSON.
    """
    recorded = load(BASELINE)
    assert recorded is not None

    result = check_freshness(
        recorded,
        extractor_version=get_extractor().version,
        normalizer_version=NORMALIZER_VERSION,
    )
    assert result.fresh, result.reason


def test_the_baseline_covers_enough_sources() -> None:
    """§7.4 asks for at least five sources.

    Below that a median describes one document's typography rather than
    anything about the extractor.
    """
    recorded = load(BASELINE)
    assert recorded is not None
    assert len(recorded.sources) >= MIN_FIXTURE_SOURCES, (
        f"{len(recorded.sources)} sources in the baseline; §7.4 asks for at "
        f"least {MIN_FIXTURE_SOURCES}"
    )


def test_the_baseline_still_describes_the_current_output(tmp_path: Path) -> None:
    """Re-measure now and compare against what was recorded.

    Freshness compares version strings, which catches a declared change. This
    catches an *undeclared* one: a chunker edit, a normalisation tweak that did
    not bump the version, a fixture that drifted. The tolerance is wide because
    the point is to catch a distribution that moved, not to pin exact numbers
    that would make every unrelated edit a failing test.
    """
    recorded = load(BASELINE)
    assert recorded is not None
    by_name = {source.name: source for source in recorded.sources}

    for name in sorted(pdfs.BUILDERS):
        if name not in by_name:
            continue
        current = _measure_fixture(tmp_path, name)
        was = by_name[name].chunk_token_median
        now = current.chunk_token_median
        assert abs(now - was) <= max(40.0, was * 0.25), (
            f"{name}: median chunk size moved from {was:.0f} to {now:.0f} "
            f"tokens with no version bump. Something changed the distribution "
            f"without declaring it -- re-run scripts/measure_extraction.py and "
            f"check the move is intended."
        )
