"""Alembic environment for the Studium data layer."""

from __future__ import annotations

import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

# The package lives one level up from migrations/.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from studium.config import settings  # noqa: E402
from studium.models import Base  # noqa: E402

config = context.config
if config.config_file_name is not None:
    # disable_existing_loggers=False, which Alembic's generated scaffolding
    # omits and which is not cosmetic.
    #
    # `fileConfig` defaults to True, and True means *every logger that already
    # exists gets `.disabled = True`*. Run in its own process -- which is how
    # `alembic upgrade head` runs in the deploy's release command -- nothing
    # else exists yet and the default is harmless. Run in-process, it silences
    # every `studium.*` logger created by an earlier import, permanently, with
    # no error and no log line saying so.
    #
    # Found by the infrastructure build: `tests/ops/test_observability.py`
    # asserts a correlation id reaches a record from `studium.agents.lecturer`,
    # and it failed only in runs where the migration-sequence tests had already
    # driven Alembic in the same process. The observability code was correct;
    # the logger it wrote to had been switched off.
    fileConfig(config.config_file_name, disable_existing_loggers=False)

# alembic.ini leaves sqlalchemy.url empty so the application and the migrations
# read one environment variable. A caller that sets the URL explicitly must
# still win: the migration tests point Alembic at a scratch database they are
# allowed to drop. Overriding unconditionally sent them to STUDIUM_DATABASE_URL
# instead -- the developer's own database -- while the fixture dropped the
# schema of a scratch database nothing then touched.
if not config.get_main_option("sqlalchemy.url", None):
    config.set_main_option("sqlalchemy.url", settings.database_url)

target_metadata = Base.metadata


def include_object(obj, name, type_, reflected, compare_to) -> bool:
    """Keep autogenerate from proposing drops for objects it cannot see.

    pgvector's HNSW index and the enum types are managed explicitly in 0001;
    reflection round-trips them imperfectly, and a spurious drop in an
    autogenerated revision is exactly the kind of thing section 13's
    review-by-hand rule exists to catch. Excluding them keeps the diff honest.
    """
    if type_ == "index" and name == "idx_source_chunk_embeddings_hnsw":
        return False
    return True


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
        # A misconfigured URL must fail rather than hang. Without this, pointing
        # at a host that drops packets instead of refusing them blocks on the OS
        # TCP timeout, which looks exactly like a stuck migration.
        connect_args={"connect_timeout": 10},
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            compare_type=True,
            compare_server_default=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
