"""Daily cost roll-up into ``cost_ledger`` (spec v1.1 §6.12).

Five sources, each with its own attribution rule:

===============================  =============================================
``agent_traces``                 the trace's own user
``content_artifacts``            the learner whose session triggered it, else
                                 the system account
``ingestion_jobs``               the uploader of the source, else the system
                                 account
``session_summaries``            the session's owner
``assessment_attempts``          the attempt's owner
===============================  =============================================

Each writes its own ``cost_*_usd`` column; ``cost_usd`` is generated by the
database as their sum and is never written here -- Postgres rejects an
``ON CONFLICT`` update that targets a generated column, which is exactly the
guard that keeps the total honest.

Idempotent: re-running a day recomputes every category from source rather than
adding to it, so a failed or partial run is fixed by running it again.
"""

from __future__ import annotations

import datetime as dt

from sqlalchemy import text
from sqlalchemy.orm import Session

from ..models.identity import SYSTEM_USER_ID

#: Token counts come only from agent traces -- the other four sources record
#: cost but not usage -- so the token columns are set by the agent statement
#: and left alone by the rest.
ROLLUP_AGENT = text(
    """
    INSERT INTO cost_ledger AS cl (
        user_id, day, model,
        tokens_in, tokens_out, cache_read_tokens,
        cache_write_5m_tokens, cache_write_1h_tokens,
        cost_agent_usd, session_count
    )
    SELECT t.user_id,
           (t.created_at AT TIME ZONE 'UTC')::date AS day,
           t.model,
           SUM(t.tokens_in),
           SUM(t.tokens_out),
           SUM(t.cache_read_tokens),
           SUM(t.cache_write_5m_tokens),
           SUM(t.cache_write_1h_tokens),
           SUM(t.cost_usd),
           COUNT(DISTINCT st.session_id)
      FROM agent_traces t
      JOIN session_turns st ON st.id = t.session_turn_id
     WHERE t.created_at >= :start AND t.created_at < :end
     GROUP BY t.user_id, day, t.model
    ON CONFLICT (user_id, day, model) DO UPDATE
       SET tokens_in             = EXCLUDED.tokens_in,
           tokens_out            = EXCLUDED.tokens_out,
           cache_read_tokens     = EXCLUDED.cache_read_tokens,
           cache_write_5m_tokens = EXCLUDED.cache_write_5m_tokens,
           cache_write_1h_tokens = EXCLUDED.cache_write_1h_tokens,
           cost_agent_usd        = EXCLUDED.cost_agent_usd,
           session_count         = EXCLUDED.session_count
    """
)

#: Attributed through the triggering session; NULL means Curator-initiated
#: pre-generation, which belongs to the system account rather than to any
#: learner's budget.
ROLLUP_CONTENT = text(
    """
    INSERT INTO cost_ledger AS cl (user_id, day, model, cost_content_usd)
    SELECT COALESCE(ls.user_id, CAST(:system_user_id AS uuid)),
           (ca.generated_at AT TIME ZONE 'UTC')::date AS day,
           COALESCE(ca.model, 'unknown'),
           SUM(ca.cost_usd)
      FROM content_artifacts ca
      LEFT JOIN learning_sessions ls ON ls.id = ca.generated_for_session_id
     WHERE ca.generated_at >= :start AND ca.generated_at < :end
       AND ca.cost_usd IS NOT NULL
     GROUP BY 1, day, 3
    ON CONFLICT (user_id, day, model) DO UPDATE
       SET cost_content_usd = EXCLUDED.cost_content_usd
    """
)

#: Corpus imports have no uploader; they are infrastructure, not a learner's
#: spend.
ROLLUP_INGESTION = text(
    """
    INSERT INTO cost_ledger AS cl (user_id, day, model, cost_ingestion_usd)
    SELECT COALESCE(s.uploaded_by, CAST(:system_user_id AS uuid)),
           (j.finished_at AT TIME ZONE 'UTC')::date AS day,
           'pipeline:ingestion',
           SUM(j.cost_usd)
      FROM ingestion_jobs j
      JOIN sources s ON s.id = j.source_id
     WHERE j.finished_at >= :start AND j.finished_at < :end
     GROUP BY 1, day
    ON CONFLICT (user_id, day, model) DO UPDATE
       SET cost_ingestion_usd = EXCLUDED.cost_ingestion_usd
    """
)

ROLLUP_SUMMARY = text(
    """
    INSERT INTO cost_ledger AS cl (user_id, day, model, cost_summary_usd)
    SELECT ls.user_id,
           (ss.generated_at AT TIME ZONE 'UTC')::date AS day,
           'pipeline:summary',
           SUM(ss.cost_usd)
      FROM session_summaries ss
      JOIN learning_sessions ls ON ls.id = ss.session_id
     WHERE ss.generated_at >= :start AND ss.generated_at < :end
     GROUP BY ls.user_id, day
    ON CONFLICT (user_id, day, model) DO UPDATE
       SET cost_summary_usd = EXCLUDED.cost_summary_usd
    """
)

#: user_id IS NOT NULL excludes attempts already anonymised by an erasure --
#: their cost was rolled up while the learner still existed, and re-attributing
#: it now would book a real charge against the system account.
ROLLUP_GRADING = text(
    """
    INSERT INTO cost_ledger AS cl (user_id, day, model, cost_grading_usd)
    SELECT a.user_id,
           (a.graded_at AT TIME ZONE 'UTC')::date AS day,
           'pipeline:grading',
           SUM(a.grading_cost_usd)
      FROM assessment_attempts a
     WHERE a.graded_at >= :start AND a.graded_at < :end
       AND a.grading_cost_usd IS NOT NULL
       AND a.user_id IS NOT NULL
     GROUP BY a.user_id, day
    ON CONFLICT (user_id, day, model) DO UPDATE
       SET cost_grading_usd = EXCLUDED.cost_grading_usd
    """
)

STATEMENTS = (
    ("agent", ROLLUP_AGENT),
    ("content", ROLLUP_CONTENT),
    ("ingestion", ROLLUP_INGESTION),
    ("summary", ROLLUP_SUMMARY),
    ("grading", ROLLUP_GRADING),
)


#: Content generated with no requesting session books to the system account.
#: That is correct for Curator pre-generation and wrong for anything a learner
#: triggered -- and the two are indistinguishable once the row is written, so
#: the job reports the count rather than absorbing it silently.
#:
#: The exposure is real because spec v1.1 §6.4 does not carry
#: ``generated_for_session_id``: a content pipeline written from the spec alone
#: will never set it, and every artifact it produces will land here. Watch this
#: number; a non-trivial value on a day with no pre-generation means the
#: pipeline is not populating the column.
UNATTRIBUTED_CONTENT = text(
    """
    SELECT count(*)
      FROM content_artifacts
     WHERE generated_at >= :start AND generated_at < :end
       AND cost_usd IS NOT NULL
       AND generated_for_session_id IS NULL
    """
)


def roll_up_day(session: Session, day: dt.date) -> dict[str, int]:
    """Roll one UTC day into the ledger.

    Returns rows touched per source, plus ``unattributed_content``: artifacts
    whose cost fell back to the system account for want of a triggering
    session. Callers should surface that figure rather than discard it.
    """
    start = dt.datetime.combine(day, dt.time.min, tzinfo=dt.UTC)
    window = {
        "start": start,
        "end": start + dt.timedelta(days=1),
        "system_user_id": SYSTEM_USER_ID,
    }
    counts = {
        name: int(session.execute(statement, window).rowcount or 0)
        for name, statement in STATEMENTS
    }
    counts["unattributed_content"] = int(
        session.execute(UNATTRIBUTED_CONTENT, window).scalar_one()
    )
    session.commit()
    return counts


def reconcile(session: Session, day: dt.date) -> dict[str, dict[str, float]]:
    """The day's recorded totals, for comparison against the provider's report.

    §9 describes reconciling "the trace count to invoice line items". Billing
    does not expose per-call line items -- usage and cost are reported in
    aggregate by day, model and key -- so the comparison that can actually be
    made is aggregate tokens and cost per model per day. The caller diffs this
    against the usage report.

    Only the agent-trace category is included: the other four are internal
    attributions of the same underlying calls or of non-metered work, and
    including them would double-count against a provider invoice.
    """
    sql = text(
        """
        SELECT model,
               SUM(tokens_in)      AS tokens_in,
               SUM(tokens_out)     AS tokens_out,
               SUM(cost_agent_usd) AS cost_usd
          FROM cost_ledger
         WHERE day = :day
           AND cost_agent_usd > 0
         GROUP BY model
        """
    )
    return {
        row.model: {
            "tokens_in": int(row.tokens_in),
            "tokens_out": int(row.tokens_out),
            "cost_usd": float(row.cost_usd),
        }
        for row in session.execute(sql, {"day": day})
    }


def refresh_decay(session: Session) -> int:
    """Recompute ``concept_mastery.p_known_decayed`` for every row.

    Daily. Gating does not depend on this being fresh -- ``graph.unlock_status``
    computes decay in SQL -- but the column drives sorting and reporting.
    """
    from ..mastery import DECAY_HALF_LIFE

    result = session.execute(
        text(
            """
            UPDATE concept_mastery
               SET p_known_decayed = LEAST(1.0, GREATEST(0.0,
                   p_known * pow(0.5,
                       EXTRACT(EPOCH FROM (NOW() - last_evidence_at))
                       / :half_life_seconds)))
             WHERE last_evidence_at IS NOT NULL
            """
        ),
        {"half_life_seconds": DECAY_HALF_LIFE.total_seconds()},
    )
    session.commit()
    return int(result.rowcount or 0)
